name: Playwright Tests
on:
  push:
    branches: [develop]
  pull_request:
    branches: [develop]
jobs:
  test:
    timeout-minutes: 60
    runs-on: e2e-tests-vps
    steps:
    - uses: actions/checkout@v3
      with:
        clean: false
    - uses: actions/setup-node@v3
      with:
        node-version: 18
    - name: Extract branch name
      shell: bash
      run: echo "branch=${GITHUB_HEAD_REF:-${GITHUB_REF#refs/heads/}}" >> $GITHUB_OUTPUT
      id: extract_branch
    - name: Install dependencies
      run: npm ci
    - name: Install Playwright Browsers
      run: cd dapplet && npx playwright install --with-deps
    - name: Run Playwright tests
      env:
        TWITTER_AUTH_EMAIL: ${{ secrets.TWITTER_AUTH_EMAIL }}
        TWITTER_AUTH_USERNAME: ${{ secrets.TWITTER_AUTH_USERNAME }}
        TWITTER_AUTH_PASSWORD: ${{ secrets.TWITTER_AUTH_PASSWORD }}
        TWITTER_AUTH_BIO: ${{ secrets.TWITTER_AUTH_BIO }}
        TWITTER_TEST_POST_URL: ${{ secrets.TWITTER_TEST_POST_URL }}
        TWITTER_TEST_PROFILE_URL: ${{ secrets.TWITTER_TEST_PROFILE_URL }}
        IMAP_AUTH_HOST: ${{ secrets.IMAP_AUTH_HOST }}
        IMAP_AUTH_USER: ${{ secrets.IMAP_AUTH_USER }}
        IMAP_AUTH_PASS: ${{ secrets.IMAP_AUTH_PASS }}
        SECRET_PHRASE: ${{ secrets.SECRET_PHRASE }}
        GIT_BRANCH_NAME: eng:${{ steps.extract_branch.outputs.branch }}
      run: npm run test
    - uses: actions/upload-artifact@v3
      if: always()
      with:
        name: playwright-report
        path: playwright-report/
        retention-days: 30
